import typescript from "@rollup/plugin-typescript";
import copy from "rollup-plugin-copy2";
import json from "rollup-plugin-json";
import zip from 'rollup-plugin-zip';
import { uglify } from "rollup-plugin-uglify";
import strip from '@rollup/plugin-strip';

// 判断是否为开发环境
const isDev = () => process.env.NODE_ENV === 'development';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
https://github.com/ourongxing/ohmymn
*/
`;

// 把用户名换一下就行，亲测无法使用 ～
const dir = isDev() ? "/Users/ourongxing/Library/Containers/QReader.MarginStudyMac/Data/Library/MarginNote Extensions/marginnote.extension.ohmymn" : "./dist"
export default {
  input: ["src/main.ts"],
  output: {
    dir: dir,
    format: "iife",
    exports: "none",
    sourcemap: false,
    banner,
  },
  watch: {
    exclude: '../node_modules/**'
  },
  plugins: [
    typescript(),
    json({
      compact: true,
    }),
    copy({
      assets: [
        "mnaddon.json",
        ["assets/logo.png", "logo.png"]
      ]
    }),
    !isDev() && strip({
      include: ["**/*.ts",],
      functions: ["log"]
    }),
    !isDev() && uglify(),
    !isDev() && zip({
      file: "ohmymn.mnaddon"
    })
  ],
};
