import commonjs from "@rollup/plugin-commonjs"
import { nodeResolve } from "@rollup/plugin-node-resolve"
import strip from "@rollup/plugin-strip"
import typescript from "@rollup/plugin-typescript"
import { defineConfig } from "rollup"
import banner from "rollup-plugin-banner"
import copy from "rollup-plugin-copy"
import { terser } from "rollup-plugin-terser"
import json from "@rollup/plugin-json"
import mnaddon from "./mnaddon.json"

// 判断是否为开发环境
const isProd = process.env.NODE_ENV === "production"

// 电脑用户名
const useName = "ourongxing"

const _banner = `THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source code, please visit the github repository
https://github.com/ourongxing/ohmymn
version: ${mnaddon.version} by ${mnaddon.author}`

const dir = isProd
  ? "./dist"
  : `/Users/${useName}/Library/Containers/QReader.MarginStudyMac/Data/Library/MarginNote Extensions/marginnote.extension.ohmymn`

export default defineConfig({
  input: ["src/main.ts"],
  output: {
    dir,
    format: "iife",
    exports: "none",
    sourcemap: false
  },
  watch: {
    exclude: "../node_modules/**"
  },
  plugins: [
    typescript(),
    nodeResolve({ browser: true }),
    commonjs(),
    json(),
    isProd &&
      strip({
        include: ["**/*.ts"],
        functions: ["log"]
      }),
    isProd && terser(),
    isProd && banner(_banner),
    copy({
      targets: [
        {
          src: ["assets/logo.png", "mnaddon.json", "assets/icon"],
          dest: dir
        }
      ]
    })
  ]
})
