import typescript from "@rollup/plugin-typescript"
import copy from "rollup-plugin-copy"
import { uglify } from "rollup-plugin-uglify"
import strip from "@rollup/plugin-strip"
import banner from "rollup-plugin-banner"
import mnaddon from "./mnaddon.json"

// 判断是否为开发环境
const isProd = process.env.NODE_ENV === "production"

// 电脑用户名
const useName = "ourongxing"

const _banner = `THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source code, please visit the github repository
https://github.com/ourongxing/ohmymn
version: ${mnaddon.version} by ${mnaddon.author}`

const dir = isProd
  ? "./dist"
  : `/Users/${useName}/Library/Containers/QReader.MarginStudyMac/Data/Library/MarginNote Extensions/marginnote.extension.ohmymn`
export default {
  input: ["src/main.ts"],
  output: {
    dir,
    format: "iife",
    exports: "none",
    sourcemap: false
  },
  watch: {
    exclude: "../node_modules/**"
  },
  plugins: [
    typescript(),
    copy({
      targets: [
        {
          src: ["assets/logo.png", "mnaddon.json", "assets/icon"],
          dest: dir
        }
      ]
    }),
    isProd &&
      strip({
        include: ["**/*.ts"],
        functions: ["log"]
      }),
    isProd && uglify(),
    isProd && banner(_banner)
  ]
}
